import { CliError } from './errors'

export type ShopifyGidType =
  | 'Product'
  | 'ProductVariant'
  | 'Collection'
  | 'Customer'
  | 'Order'
  | 'CalculatedOrder'
  | 'CalculatedLineItem'
  | 'CalculatedDiscountApplication'
  | 'CalculatedShippingLine'
  | 'AppInstallation'
  | 'AppSubscription'
  | 'DiscountAutomaticNode'
  | 'DiscountCodeNode'
  | 'DiscountRedeemCode'
  | 'InventoryItem'
  | 'InventoryShipment'
  | 'InventoryTransfer'
  | 'InventoryTransferLineItem'
  | 'Location'
  | 'FulfillmentOrder'
  | 'Fulfillment'
  | 'FulfillmentHold'
  | 'FulfillmentService'
  | 'GiftCard'
  | 'Return'
  | 'ReturnLineItem'
  | 'ReturnReasonDefinition'
  | 'ReturnableFulfillment'
  | 'DeliveryProfile'
  | 'DeliveryCustomization'
  | 'DeliveryCarrierService'
  | 'File'
  | 'PaymentTerms'
  | 'PaymentTermsTemplate'
  | 'PaymentSchedule'
  | 'PriceList'
  | 'Publication'
  | 'Refund'
  | 'Article'
  | 'Blog'
  | 'Page'
  | 'Comment'
  | 'Event'
  | 'Menu'
  | 'Catalog'
  | 'Market'
  | 'Company'
  | 'CompanyContact'
  | 'CompanyContactRole'
  | 'CompanyContactRoleAssignment'
  | 'CompanyLocation'
  | 'CompanyLocationStaffMemberAssignment'
  | 'StoreCreditAccount'
  | 'DraftOrder'
  | 'DraftOrderTag'
  | 'BulkOperation'
  | 'UrlRedirect'
  | 'Segment'
  | 'SavedSearch'
  | 'ScriptTag'
  | 'CartTransform'
  | 'Validation'
  | 'OnlineStoreTheme'
  | 'CheckoutProfile'
  | 'WebPixel'
  | 'ServerPixel'
  | 'MarketingActivity'
  | 'WebhookSubscription'
  | 'MetafieldDefinition'
  | 'Metaobject'
  | 'MetaobjectDefinition'
  | 'SellingPlanGroup'
  | 'SubscriptionContract'
  | 'SubscriptionDraft'
  | 'SubscriptionLine'
  | 'SubscriptionManualDiscount'
  | 'SubscriptionBillingAttempt'

export const isGid = (value: string) => value.startsWith('gid://')

export const coerceGid = (value: string, type: ShopifyGidType) => {
  if (isGid(value)) return value
  if (!/^\d+$/.test(value)) {
    throw new CliError(
      `Expected a numeric ID or full GID for ${type}. Got: ${value}`,
      2,
    )
  }
  return `gid://shopify/${type}/${value}`
}
